export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'

//export const CREATE_POST = 'CREATE_POST';
//export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
//export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';
//export const RESET_NEW_POST = 'RESET_NEW_POST';

export const REQUEST_BOARD = 'REQUEST_BOARD';
export const BOARD_SUCCESS = 'BOARD_SUCCESS';
export const BOARD_FAILURE = 'BOARD_FAILURE';

export const RECEIVE_BOARD = 'RECEIVE_BOARD';

//PIECE ROTATION
export const ROTATE_PIECE = 'ROTATE_PIECE';
export const FLIP_PIECE = 'FLIP_PIECE';

//PIECE BOARD PLACEMENT
export const PLACE_PIECE = 'PLACE_PIECE';

export const CREATE_MOVE = 'CREATE_MOVE';
export const CREATE_MOVE_SUCCESS = 'CREATE_MOVE_SUCCESS';
export const CREATE_MOVE_FAILURE = 'CREATE_MOVE_FAILURE';


export const REQUEST_MOVES = 'REQUEST_MOVES';
export const RECEIVE_MOVES = 'RECEIVE_MOVES';


export const BUILD_BOARD = 'BUILD_BOARD';


